. ./docker/sh/color.sh

PORCENTAGE_0="${RED}* 0%${RESET}"
PORCENTAGE_10="${RED}** 10%${RESET}"
PORCENTAGE_15="${RED}*** 15%${RESET}"
PORCENTAGE_20="${RED}**** 20%${RESET}"
PORCENTAGE_25="${RED}***** 25%${RESET}"
PORCENTAGE_30="${RED}****** 30%${RESET}"
PORCENTAGE_35="${RED}******* 35%${RESET}"
PORCENTAGE_40="${RED}******** 40%${RESET}"
PORCENTAGE_45="${RED}********* 45%${RESET}"
PORCENTAGE_50="${YELLOW}********** 50%${RESET}"
PORCENTAGE_55="${YELLOW}*********** 55%${RESET}"
PORCENTAGE_60="${YELLOW}************ 60%${RESET}"
PORCENTAGE_65="${YELLOW}************* 65%${RESET}"
PORCENTAGE_70="${YELLOW}*************** 70%${RESET}"
PORCENTAGE_75="${YELLOW}**************** 75%${RESET}"
PORCENTAGE_80="${YELLOW}***************** 80%${RESET}"
PORCENTAGE_85="${YELLOW}****************** 85% ${RESET}"
PORCENTAGE_90="${YELLOW}******************* 90%${RESET}"
PORCENTAGE_95="${YELLOW}******************** 95%${RESET}"
PORCENTAGE_100="${GREEN}******************** 100%${RESET}"
